apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-mysqldb-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-mysqldb
  clusterServicePlanExternalName: basic50
  parameters:
    location: eastus
    resourceGroup: demo
    firewallRules:
    - firewallStartIPAddress: "0.0.0.0"
      firewallEndIPAddress: "255.255.255.255"
      firewallRuleName: "AllowAll"
