apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-mysql-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-mysqldb
  clusterServicePlanExternalName: basic50
  parameters:
    location: eastus
    resourceGroup: demo
