version: "3.2"
services:
  base-go-service: &base-go-service
    image: quay.io/deis/lightweight-docker-go:v0.3.0
    working_dir: /go/src/github.com/Azure/open-service-broker-azure
    environment: &base-go-environment
      CGO_ENABLED: 0
      GO111MODULE: "on"
    volumes:
    - .:/go/src/github.com/Azure/open-service-broker-azure
  test: # Like dev, but linked to redis
    <<: *base-go-service
    environment:
      <<: *base-go-environment
      STORAGE_REDIS_HOST: redis
      ASYNC_REDIS_HOST: redis
    links:
    - test-redis:redis
  test-api-compliance: #Run the API compliance tests-- osb checker linked to a dummy broker
    image: quay.io/deis/osb-checker:v0.3.0
    command: ./test.sh broker 8088 60
    volumes:
    - ./tests/api-compliance/broker-config.json:/app/config.json
    links:
    - test-api-compliance-broker:broker
  test-api-compliance-broker:
    <<: *base-go-service
    command:  bash -c 'go run cmd/compliance-test-broker/compliance-test-broker.go'
  e2e:
    <<: *base-go-service
    environment:
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      TEST_MODULES: ${TEST_MODULES}
      BASIC_AUTH_USERNAME: username
      BASIC_AUTH_PASSWORD: password
    links:
    - broker:broker
  broker:
    build: .
    environment:
      LOG_LEVEL: DEBUG
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      STORAGE_REDIS_HOST: redis
      STORAGE_REDIS_DB: 0
      ASYNC_REDIS_HOST: redis
      ASYNC_REDIS_DB: 1
      CRYPTO_ENCRYPTION_SCHEME: NOOP
      # CRYPTO_AES256_KEY: AES256Key-32Characters1234567890
      BASIC_AUTH_USERNAME: username
      BASIC_AUTH_PASSWORD: password
      MIN_STABILITY: EXPERIMENTAL
    links:
    - broker-redis:redis
  test-redis:
    image: &redis-image redis:3.2.4
  broker-redis:
    image: *redis-image
    ports:
    - "6379:6379"
