version: "3.2"
services:
  test:
    image: quay.io/deis/lightweight-docker-go:v0.2.0
    working_dir: /go/src/github.com/Azure/open-service-broker-azure
    volumes:
    - .:/go/src/github.com/Azure/open-service-broker-azure
    links:
    - test-redis:redis
  test-api-compliance: #Run the API compliance tests, run the broker, redis and the osb-checker
    build:
      context: .
      dockerfile: Dockerfile.osb-checker
    links:
    - test-api-compliance-broker:broker
  test-api-compliance-broker:
    image: quay.io/deis/lightweight-docker-go:v0.2.0
    working_dir: /go/src/github.com/Azure/open-service-broker-azure
    volumes:
    - .:/go/src/github.com/Azure/open-service-broker-azure
    command:  bash -c 'go run cmd/compliance-test-broker/compliance-test-broker.go'
  broker:
    build: .
    environment:
      LOG_LEVEL: DEBUG
      STORAGE_REDIS_HOST: redis
      STORAGE_REDIS_DB: 0
      ASYNC_REDIS_HOST: redis
      ASYNC_REDIS_DB: 1
      STORAGE_ENCRYPTION_SCHEME: NOOP
      # STORAGE_AES256_KEY: AES256Key-32Characters1234567890
      BASIC_AUTH_USERNAME: username
      BASIC_AUTH_PASSWORD: password
      MIN_STABILITY: EXPERIMENTAL
    links:
    - broker-redis:redis
  test-redis:
    image: redis:3.2.4
  broker-redis:
    image: redis:3.2.4
    ports:
    - "6379:6379"
