
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "v9.10.0"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  # krancour: We can resume using upstream logrus if/when this PR is merged:
  # https://github.com/sirupsen/logrus/pull/671
  source = "github.com/krancour/logrus"
  branch = "split-streams"

[[constraint]]
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  name = "github.com/go-redis/redis"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"

[[constraint]]
  name = "github.com/gorilla/mux"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"

[[constraint]]
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/urfave/cli"

[[constraint]]
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "github.com/Masterminds/sprig"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
