apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: example-sql-database-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-sql-database-only
  clusterServicePlanExternalName: basic
  parameters:
    parentAlias: 3e8f59b2-0f73-4a59-9c0b-6277c3e8109e
