{{- if .Values.registerBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: asb
spec:
  url: http://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  authInfo:
    basicAuthSecret:
      kind: Secret
      name: "{{ template "fullname" . }}-auth"
      namespace: {{ .Release.Namespace | quote }}
{{- end }}
