apiVersion: v1
kind: Secret
metadata:
  name: deisci-jimz-testing-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaR1ZwYzJOcEsycHBiWHBmZEdWemRHbHVaenBTVFRkVlN6Rk5VMDFLV1ZkUFFWSkxPVXhaTmxCVFdWQkRORWRRVHpNME5USXpNMG8xVUVORVdFUlVUa3BaVWtoYU5EaFlRazFETmxsUlRUVXpOemhWIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
